server:
  port: 8866

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://121.30.226.57:43306/intellectual?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.doctor.app.entity




serveraddress: http://39.97.187.244

